<?php
namespace app\index\model;
use think\Model;

class User extends Model{

    protected $pk = 'id';
    protected $name = 'user';

    protected function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function setUser($value){
        return $value;
    }
}

?>